from app.services.auth import authenticate_user
from app.services.user import (
    get_user,
    get_user_by_email,
    get_users,
    create_user,
    update_user_admin,
    update_user_profile,
    deactivate_user,
)
from app.services.customer import (
    get_customer,
    get_customer_by_phone,
    get_customers,
    create_customer,
    update_customer,
    delete_customer as delete_customer_service,
)
from app.services.platform import (
    get_platform,
    get_platform_by_name,
    get_platform_by_code,
    get_platforms,
    create_platform,
    update_platform,
    delete_platform as delete_platform_service,
)
from app.services.call import (
    get_call,
    get_calls,
    create_call,
    update_call,
    start_call,
    complete_call,
    assign_call,
    update_call_status,
    delete_call as delete_call_service,
)
from app.services.call_outcome import (
    get_call_outcome,
    get_call_outcome_by_call_id,
    get_call_outcomes,
    create_call_outcome,
    update_call_outcome,
    delete_call_outcome as delete_call_outcome_service,
)
from app.services.follow_up import (
    get_follow_up,
    get_follow_ups,
    get_follow_ups_by_call_id,
    create_follow_up,
    update_follow_up,
    delete_follow_up as delete_follow_up_service,
)
from app.services.call_analytics import (
    get_call_summary,
    get_call_outcome_summary,
    get_follow_up_summary,
    get_agent_call_performance,
    get_call_analytics,
)
from app.services.call_dashboard import (
    get_dashboard_summary,
    get_recent_calls,
    get_call_activity,
    get_upcoming_follow_ups,
    get_recent_outcomes,
    get_call_dashboard,
)
from app.services.notification import (
    create_notification,
    get_notification,
    get_user_notifications,
    get_notification_summary,
    mark_as_read,
    mark_all_as_read,
    delete_notification as delete_notification_service,
)
from app.services.audit_log import (
    create_audit_log,
    log_activity,
    get_audit_logs,
    get_audit_log,
)
from app.services.report import (
    get_call_report,
    get_customer_report,
    get_outcome_report,
    get_follow_up_report,
    get_agent_performance_report,
    get_audit_report,
    get_report_summary,
    export_to_csv_response,
)

__all__ = [
    "authenticate_user",
    "get_user",
    "get_user_by_email",
    "get_users",
    "create_user",
    "update_user_admin",
    "update_user_profile",
    "deactivate_user",
    "get_customer",
    "get_customer_by_phone",
    "get_customers",
    "create_customer",
    "update_customer",
    "delete_customer_service",
    "get_platform",
    "get_platform_by_name",
    "get_platform_by_code",
    "get_platforms",
    "create_platform",
    "update_platform",
    "delete_platform_service",
    "get_call",
    "get_calls",
    "create_call",
    "update_call",
    "start_call",
    "complete_call",
    "assign_call",
    "update_call_status",
    "delete_call_service",
    "get_call_outcome",
    "get_call_outcome_by_call_id",
    "get_call_outcomes",
    "create_call_outcome",
    "update_call_outcome",
    "delete_call_outcome_service",
    "get_follow_up",
    "get_follow_ups",
    "get_follow_ups_by_call_id",
    "create_follow_up",
    "update_follow_up",
    "delete_follow_up_service",
    "get_call_summary",
    "get_call_outcome_summary",
    "get_follow_up_summary",
    "get_agent_call_performance",
    "get_call_analytics",
    "get_dashboard_summary",
    "get_recent_calls",
    "get_call_activity",
    "get_upcoming_follow_ups",
    "get_recent_outcomes",
    "get_call_dashboard",
    "create_notification",
    "get_notification",
    "get_user_notifications",
    "get_notification_summary",
    "mark_as_read",
    "mark_all_as_read",
    "delete_notification_service",
    "create_audit_log",
    "log_activity",
    "get_audit_logs",
    "get_audit_log",
    "get_call_report",
    "get_customer_report",
    "get_outcome_report",
    "get_follow_up_report",
    "get_agent_performance_report",
    "get_audit_report",
    "get_report_summary",
    "export_to_csv_response",
]
