"""create call outcomes table

Revision ID: 6f98323d30d2
Revises: 1b90a4f1f117
Create Date: 2026-08-24 10:54:12.980669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f98323d30d2'
down_revision: Union[str, Sequence[str], None] = '1b90a4f1f117'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('call_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('call_id', sa.Integer(), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_outcomes_call_id'), 'call_outcomes', ['call_id'], unique=True)
    op.create_index(op.f('ix_call_outcomes_created_by'), 'call_outcomes', ['created_by'], unique=False)
    op.create_index(op.f('ix_call_outcomes_id'), 'call_outcomes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_outcomes_id'), table_name='call_outcomes')
    op.drop_index(op.f('ix_call_outcomes_created_by'), table_name='call_outcomes')
    op.drop_index(op.f('ix_call_outcomes_call_id'), table_name='call_outcomes')
    op.drop_table('call_outcomes')
    # ### end Alembic commands ###
